jack-ullery/AppAnvil

CMakeLists.txt
resources/status.glade
src/main.cc
src/main_window.h
src/tabs/parser.cc
src/tabs/parser.h
src/tabs/profiles.cc
src/tabs/profiles.h
src/tabs/status.cc
src/tabs/status.h
src/tabs/status_column_record.cc
src/tabs/status_column_record.h
usr.bin.firefox

Added 3 selection options to the dropdown menu (Enforce, Complain, Disable) which issue 'aa-enforce', 'aa-complain', and 'aa-disable' commands respectfully.
Added the ability to filter out paths with specified flags in the parser. More specifically, the transition-to-subprofile flags which were causing duplicate paths to be returned.
Note: we're still using the old way of simply just issuing console commands which seems to break for certain profiles including ones with 'snap', double slashes, and, more recently, Discord for some reason.

dropdown menu functionality + parser improvements

---

.github/workflows/build.yml

I split the `build.yml` workflow into two _Jobs_. The first job builds AppAnvil, and saves the result as an artifact. The second job runs the unit tests, and checks that they pass.
I also removed the code auto-formatting for now, and may re-add that functionality when #21 is fixed.
This layout looks nicer when reviewing the workflow run results. It would be also good to create a separate job (or workflow file) to push the built code to the **Releases** section. Furthermore, we may want to build and test the project on multiple platforms.
I made multiple commits to GitHub to develop and test the functionality of my changes. When I merge, I'll probably make a squash commit, to not pollute the history.

Update GitHub Workflows

---

.gitignore
CMakeLists.txt

This is a small commit that changes `CMakeLists.txt` to enable packaging AppAnvil into a `.deb` file. I meant to push this change directly to main, but accidentally put it onto this branch.

Support DEB packaging

---

src/tabs/model/process_adapter.cc
src/tabs/model/profile_adapter.cc

This fixes a minor bug that would prevent _ProcessTableEntries_ and _ProfileTableEntries_ from being modified, after they were added to the table. After this PR is merged, all the unit-tests should finally pass.

Fix bug in ProfileAdapter + ProcessAdapter

---

src/tabs/controller/logs_controller.cc
src/tabs/controller/logs_controller.h
src/threads/dispatcher_middleman.cc
test/src/tabs/controller/logs_controller_test.cc

Previously, we had an issue where the _Logs_ tab would freeze when loading it for the first time. This would happen, because it takes a long time to read and parse a large number of logs.  
I changes how _LogsController_ parses logs. Previously, it parsed all the logs in one long for-loop. Now, it parses the logs in batches of 128 logs.  
When the `add_data_to_record(..))` method is called, it creates an idle function to parse logs when nothing else is happening. This means that, whenever the application is in use (for example if the user is clicking buttons), the idle function waits to be called. Eventually, when the function is finally called: it only parses 128 logs, and waits until the main loop is ready to call it again. 
Now the _Logs_ tab can be populated without freezing the …

Fix issue #22

---

.github/workflows/format.yml
CMakeLists.txt

This is a continuation of #33. This action (if it works correctly) should automatically format and push code when PRs are made. 
This could be useful, because it ensures code is properly formatted before code review. 
The action is triggered by [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) which can sometimes be [problematic](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). However, it is written in a way to avoid those issues.

Auto-Format code on Pull Request

---

.github/workflows/format.yml

This fixes an error introduced by PR #34, which called _clang-format_ in an incorrect way. The error would prevent the code from being formatted correctly. This fix should change that.

Fix error with auto-format code action

---

.github/workflows/build.yml
.gitignore
CMakeLists.txt
README.md
test/CMakeLists.txt

These changes modify the build, so that code coverage reports can now be captured easily. A code coverage report can be generated by running `make report`. Afterwards, you can view the HTML report by opening the `./report/index.html` file.
I also changed the build process for the unit tests. Previously, the unit test would be built automatically with the main binary. Now, you must explicitly build the unit tests using `make test`. In doing this, the name of the resulting test binary changed from `./dist/appanvil_test` to `./dist/test` 
Updates were made to both [github/workflows/build.yml](https://github.com/jack-ullery/AppAnvil/blob/d570f70efc07a56c482ab63e17184112b211d590/.github/workflows/build.yml) and [README.md](https://github.com/jack-ullery/AppAnvil/blob/code-coverage/README.md) …

Capture code coverage reports

---

src/tabs/view/common.h
src/tabs/view/help.cc
src/tabs/view/help.h
src/tabs/view/info_box.cc
src/tabs/view/info_box.h
src/tabs/view/logs.cc
src/tabs/view/logs.h
src/tabs/view/profile_loader.cc
src/tabs/view/profile_loader.h
src/tabs/view/profiles.cc
src/tabs/view/profiles.h
src/tabs/view/status.cc
src/tabs/view/status.h

This is a simple PR which cleans code by moving the `get_widget` and `get_widget_shared` functions to a separate class. Previously, there were copies of this function repeated in multiple classes. This fixes that.

Common view functions

---

resources/help.glade
src/main_window.cc
src/main_window.h
src/tabs/view/help.cc
src/tabs/view/help.h

This PR formats the headers in the Help page to match the headers in other places of the GUI. It also removes the button at the bottom of the Help page, which was used to exit the page.

Reformat help page

---

resources/profile.glade
src/tabs/controller/logs_controller.cc
src/tabs/controller/processes_controller.cc
src/tabs/model/profile_adapter.cc
src/tabs/view/profiles.cc
src/threads/command_caller.cc
test/src/tabs/view/profiles_test.cc
test/src/tabs/view/profiles_test.h

This PR allows the user to switch an AppArmor profile to _Audit_ mode. According to AppArmor developers, this confinement mode should only be used sparingly, most likely because it can pollute the system logs with unimportant data. We might want to communicate this to the users somehow.
The [AppArmor wiki](https://gitlab.com/apparmor/apparmor/-/wikis/manpage_aa-audit.8#description) explains the functionality for this confinement mode: "In this mode security policy is enforced and all access (successes and failures) are logged to the system log"
I found a few regressions that were not caught by the unit tests, which prevented the user from correctly changing a profiles status. This PR should fix those bugs
This was pretty simple, and involved making a call to `aa-enforce`
Previously, …

Audit mode

---

aa-caller/src/aa-caller.cc
aa-caller/src/aa-caller.h
aa-caller/src/main.cc
resources/com.github.jack-ullery.AppAnvil.pkexec.policy
src/main_window.cc
src/threads/command_caller.cc
src/threads/command_caller.h
src/threads/log_reader.cc
src/threads/log_reader.h

This allows AppAnvil to read additional logs from auditd.
Added a flag "-l" to aa-caller. When `aa-caller -l` is executed, it calls ausearch to return a list of logs that may pertain to apparmor. Some of the logs might not be apparmor related. 
Furthermore, this generates a randomly named checkpoint file that ausearch can use to save progress. The file's name has the following format: `/tmp/appanvil_[random]`, where [random] is a random number. This filename is printed on the first line of output from aa-caller. Afterwards, the user can execute `aa-caller -l [filename]` to get any new logs. See the _checkpoint_ option in `man ausearch` for more information.
Now the _LogReader_ class also queries aa-caller when reading logs. So that they are shown in AppAnvil.
I noticed that the pkexec …

Read logs from auditd

---

resources/profile.glade
src/main_window.cc
src/main_window.h
src/tabs/controller/profile_modify_controller.cc
src/tabs/controller/profiles_controller.cc
src/tabs/controller/profiles_controller.h
src/tabs/model/profile_adapter.cc
src/tabs/model/profile_adapter.h
src/tabs/model/status_column_record.h
src/tabs/view/profiles.cc
src/tabs/view/profiles.h
src/threads/command_caller.cc
src/threads/dispatcher_middleman.cc

This PR modifies how users will change the status of a profile.
Instead of clicking a button in the right pane of the Profile tab, users can modify the status of a Profile by directly interacting with the row. Clicking on a row's "Status" cell will open a Combobox where users can select which status they want to change the Profile to.

Change status

---

src/tabs/column_header.h
src/tabs/controller/processes_controller.cc
src/tabs/controller/profile_modify_controller.cc
src/tabs/controller/profile_modify_controller.h
src/tabs/controller/profiles_controller.cc
src/tabs/model/profile_adapter.cc
src/tabs/view/profile_modify.cc
src/tabs/view/profile_modify.h

This fixes issue #53.
For some reason, initializing _combobox_options_ with braces led to a compilation error on Arch-based distributions. I think this might have something to do with the version of clang Arch uses, but I am not sure. Regardless, using parenthesis to construct the field fixed the issue.
I also found and fixed another Arch specific error when testing. It seems `ps` can sometimes return an underscore for "context" when a process is unconfined. This was leading to an issue when using regular exceptions to parse its output. I fixed the issue and made the regex parsing more resilient to exceptions.

Fix build for Arch

---

aa-caller/src/aa-caller.h
src/threads/command_caller.cc

Hi, I was trying AppAnvil (compiled from source and installed in /usr/local/bin/) and i noticed this bug: the program would not display any profile or processes, and this error would come up:
> Error calling 'pkexec'. Cannot run program aa-caller: No such file or directory
i.e. pkexec cannot find the aa-caller binary in /usr/local/bin.
The following line in command_caller.cc (CommandCaller::call_command):
> std::vector<std::string> envp = { "/usr/bin/", "/usr/sbin/", "/usr/local/bin" };
doesn't work because the envp parameter of Glib::spawn_sync expects a vector of environment variables (with the syntax variable=value)
This pull request fixes the problem by setting PATH correctly for spawned processes.

Fix environment variables of processes spawned with call_command

---

aa-caller/src/aa-caller.cc
resources/help.glade
src/main_window.cc
src/main_window.h
src/tabs/model/log_adapter.h
src/tabs/view/help.cc
src/tabs/view/help.h

Previously, when users pressed the "Help" button (labeled with a question mark), a page appeared to describe a set of topics related to AppArmor. 
In my opinion, that page was hard to read and not very helpful. In particular, we should limit the amount of information that is thrust onto the user at one time.
I made some changes so that the "Help" button now opens a small popup box, instead of an entire page. The contents of this popup box change depending on what tab AppAnvil is displaying. Currently, the box explains AppArmor terminology that may be unknown or confusing to a novice user.
Eventually, I would like to tailor help information for other pages, like the "Profile Modify" page. I am also considering adding a section to explain the types of actions a user can perform using …

Help Popup

---

.gitignore
CMakeLists.txt
resources/pkexec.policy.in

Previously, there has been an issue where the pkexec policy would not apply to some builds. The default CMake install prefix is `/usr/local`. However, the pkexec policy would only apply if the build prefix was changed to `/usr`.
I modified the policy file to be configured automatically by CMake, so that the it will always point to the correct aa-caller binary when installed.

Configurable pkexec

---

resources/profile_modify.glade
src/tabs/controller/profile_modify_controller.cc
src/tabs/controller/profile_modify_controller.h
src/tabs/view/profile_modify.cc
src/tabs/view/profile_modify.h
src/threads/command_caller.cc

This PR closes #56.
Now when a user makes changes to a profile, those changes are staged (but not automatically applied) by the _AppArmor::Parser_ class in [libappanvil](https://github.com/jack-ullery/libappanvil). Two buttons appear at the bottom of the screen that allow the user to either cancel the changes or apply them to the system.
Internally the logic for cancelling/applying changes is handled by libappanvil. Additionally, libappanvil can determine if there are any unsaved changes. In libappanvil I created a binary called "aa-replace" which saves a profile and loads it using "apparmor_parser".
I also added a GtkRevealer to automatically hide/show the cancel/apply buttons. These buttons should only be visible if there are staged changes to the profile.
I am considering creating a …

Add cancel/apply buttons to ProfileModify 

---

CMakeLists.txt
resources/appanvil.desktop.in

Resolves issue #66.
Almost all linux distributions use .../share/applications for storing desktop entries. I also checked how other projects handle installing them and they all just hardcode this path. I don't think it would be an issue, but if there will be a need to improve it, I'll try to handle that.
I also added project version variable for tracking purposes.

Added desktop entry

---

CMakeLists.txt
src/tabs/controller/profile_loader_controller.cc
src/tabs/controller/profile_loader_controller.h
src/tabs/view/profiles.cc
src/tabs/view/profiles.h

This fixes #54, by reintroducing _ProfileLoaderController_ which was deleted in de5f8b79e8433ea305ee88601ce5f0ad9947bf14.
There was also a minor fix to improve the linking for this controller.

Fix 'Load Profile' page

---

resources/profile_modify.glade
src/tabs/controller/profile_modify_controller.cc
src/tabs/view/profile_modify.cc
src/tabs/view/profile_modify.h

This change allows the user to manually edit, parse, and apply changes to a Profile, by using the "Profile Text" section on the "Profile Modify" page. They can do this by pressing the "Parse" button which will appear if there were any manual changes entered into the text area. Afterwards, they much select "Apply" to save and apply the modified profile to the system (like they would if changing the profile through another screen).
This two-step process might be a little unintuitive, but it was the best solution I could come up with given technical constraints. The main problem I had was: when should changes made in this editor be parsed? Should I reparse them continuously every time a key is pressed (maybe waiting for a timeout), or should I allow the user to manually choose? If I choose …

Save manually edited profile

---

CMakeLists.txt
resources/ui/apparmor_not_installed.glade
resources/ui/resources.gresource.xml
src/main.cc
src/tabs/view/apparmor_not_installed.cc
src/tabs/view/apparmor_not_installed.h
src/threads/command_caller.cc
src/threads/command_caller.h
test/src/threads/command_caller.cc

Solves #85 by using `aa-enabled` to see if AppArmor is running. 
If `aa-enabled` exits with a non-zero status code, we then create a dialog box informing the user that AppArmor is not installed. This check is run in `main.cc`, before the MainWindow is built.

Add warning message when AppArmor is not enabled

---

test/CMakeLists.txt

The `gtest_add_tests` macro is very old and breaks when building on newer versions of CMake (in my case cmake 3.31.4-1 on ArchLinux). 
Switching to `gtest_discover_tests` and omitting the `SOURCES` option works, but whichever is causing the issue is unclear. 
By the way, doing this seems to automatically ignore the unused tests, which is a plus in my book.
I'm pasting the results from running `make test` to prove that no regression is introduced. 
**Before:**
```
95% tests passed, 72 tests failed out of 1584
```
**After:**
```
99% tests passed, 2 tests failed out of 1514
```

Update CMake test config

---

src/tabs/controller/profiles_controller.cc
src/tabs/model/profile_adapter.cc
src/tabs/model/profile_adapter.h

This fixes #99 by only updating the TreeView when there are new/different profiles.
Since this doesn't affect the other Processes/Logs screen, all I had to do was modify the ProfilesController class to be more careful when it calls _refresh()_.

Only update TreeView when data is changed
